### ISSUE TITLE
Issue with the script

### ISSUE THREAD

**Issue by Debi-sys** [fu-volodya/DosForUkraine#1]
Trying to run the script in docker provides me with an output of

`: not foundsts.sh: line 2: 

/send_requests.sh: line 12: syntax error: unexpected end of file (expecting "do")`

any idea of what i did wrong?

**Comment by fu-volodya** [comment]
Could you show me the full commandline you are running?

**Comment by Debi-sys** [comment]
i first installed docker and git on my PC, then i cloned this program and ran `docker-compose build` since `docker-composed --build` outputted `unknown flag: --build`, the output for docker-composed --build was 
`[+] Building 6.9s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 193B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/alpine:3.15.0                                                   3.1s
 => [1/3] FROM docker.io/library/alpine:3.15.0@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8  0.1s
 => => resolve docker.io/library/alpine:3.15.0@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8  0.0s
 => => sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 1.64kB / 1.64kB                     0.0s
 => => sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3 528B / 528B                         0.0s
 => => sha256:c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18 1.47kB / 1.47kB                     0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 342B                                                                                  0.0s
 => [2/3] RUN apk update && apk --no-cache add curl                                                                3.4s
 => [3/3] COPY send_requests.sh send_requests.sh                                                                   0.0s
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.1s
 => => writing image sha256:fa45d71cd33b6aaa94f2fff2ed216bd1e851af5ff1fdc445859140260582145b                       0.0s
 => => naming to docker.io/library/dosforukraine_requester                                                         0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them` then i tried to run the app in docker desktop which outputted the original issue.

**Comment by fu-volodya** [comment]
ugh. there was a stupid typo in the instructions. the command is supposed to be `docker-compose up --build`
thank you. let me know if you got it working now.
